[TILING_SCHEME]
# All TILING_SCHEME properties (except of CRS) refers to zoom level 0
EPSG_CRS=3857
TOP_LEFT_X=-20037508.3427892
TOP_LEFT_Y=20037508.3427892
TILE_DIM=40075016.6855784
MATRIX_WIDTH=1
MATRIX_HEIGHT=1
SCALE=419311712

[GDAL_OPTIONS]
COMPRESS="NO"
SIMLIFICATION=0
SIMPLIFICATION_MAX_ZOOM=0

[GENERAL_CONF]
DATA_SIMPLIFICATION_TOLERANCE=1 # CRS Units
REMOVE_DUPLICATES_DISTANCE=150 # Points